<?php

namespace Database\Seeders;

use App\Models\Shop;
use Illuminate\Database\Seeder;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        $shops = [
            [
                'name' => 'Bomet Branch',
                'code' => 'KPFC-002',
                'address' => 'Bomet Town',
                'latitude' => -0.778704,
                'longitude' => 35.340683,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Bungoma Branch',
                'code' => 'KPFC-003',
                'address' => 'Bungoma Town',
                'latitude' => 0.565219,
                'longitude' => 34.561966,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Eldoret Branch',
                'code' => 'KPFC-004',
                'address' => 'Eldoret Town',
                'latitude' => 0.522291,
                'longitude' => 35.253833,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Embu Branch',
                'code' => 'KPFC-005',
                'address' => 'Embu Town',
                'latitude' => -0.542832,
                'longitude' => 37.455505,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Gilgil Branch',
                'code' => 'KPFC-006',
                'address' => 'Gilgil Town',
                'latitude' => -0.497628,
                'longitude' => 36.319689,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kamangu Branch',
                'code' => 'KPFC-007',
                'address' => 'Kamangu Town',
                'latitude' => -1.241452,
                'longitude' => 36.600638,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kawangware Branch',
                'code' => 'KPFC-009',
                'address' => 'Kawangware Town',
                'latitude' => -1.284024,
                'longitude' => 36.729979,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kericho Branch',
                'code' => 'KPFC-010',
                'address' => 'Kericho Town',
                'latitude' => -0.365813,
                'longitude' => 35.290284,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kiambu Branch',
                'code' => 'KPFC-011',
                'address' => 'Kiambu Town',
                'latitude' => -1.156601,
                'longitude' => 36.815261,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kiserian Branch',
                'code' => 'KPFC-012',
                'address' => 'Kiserian Town',
                'latitude' => -1.433972,
                'longitude' => 36.685603,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kisii Branch',
                'code' => 'KPFC-013',
                'address' => 'Kisii Town',
                'latitude' => -0.677703,
                'longitude' => 34.775168,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kitale Branch',
                'code' => 'KPFC-014',
                'address' => 'Kitale Town',
                'latitude' => 1.005406,
                'longitude' => 35.008716,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Lexo Branch',
                'code' => 'KPFC-015',
                'address' => 'Kikuyu Town',
                'latitude' => -1.23878,
                'longitude' => 36.66647,
                'radius_meters' => 200,
                'active' => true,
            ],
            [
                'name' => 'Limuru Branch',
                'code' => 'KPFC-016',
                'address' => 'Limuru Town',
                'latitude' => -1.106027,
                'longitude' => 36.637538,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Machakos Branch',
                'code' => 'KPFC-017',
                'address' => 'Machakos Town',
                'latitude' => -1.5181221,
                'longitude' => 37.265393,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Maimahiu Branch',
                'code' => 'KPFC-018',
                'address' => 'Maimahiu Town',
                'latitude' => -0.987888,
                'longitude' => 36.591738,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Main Shop',
                'code' => 'KPFC-019',
                'address' => 'Kikuyu Town',
                'latitude' => -1.2406854,
                'longitude' => 36.6652482,
                'radius_meters' => 200,
                'active' => true,
            ],
            [
                'name' => 'Malindi Branch',
                'code' => 'KPFC-020',
                'address' => 'Malindi Town',
                'latitude' => -3.226638,
                'longitude' => 40.107602,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Kitengela Branch',
                'code' => 'KPFC-021',
                'address' => 'Kitengela Town',
                'latitude' => -1.514897,
                'longitude' => 36.949062,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Molo Branch',
                'code' => 'KPFC-022',
                'address' => 'Molo Town',
                'latitude' => -0.2480844,
                'longitude' => 35.7322053,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Mtwapa Branch',
                'code' => 'KPFC-023',
                'address' => 'Mtwapa Town',
                'latitude' => -3.918786,
                'longitude' => 39.757596,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => "Murang'a Branch",
                'code' => 'KPFC-024',
                'address' => "Murang'a Town",
                'latitude' => -0.725374,
                'longitude' => 37.161448,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Naivasha Branch',
                'code' => 'KPFC-025',
                'address' => 'Naivasha Town',
                'latitude' => -0.748037,
                'longitude' => 36.466026,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Nakuru Branch',
                'code' => 'KPFC-026',
                'address' => 'Nakuru Town',
                'latitude' => -0.291806,
                'longitude' => 36.120417,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Nanyuki Branch',
                'code' => 'KPFC-027',
                'address' => 'Nanyuki Town',
                'latitude' => -0.0061,
                'longitude' => 37.068881,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Narok Branch',
                'code' => 'KPFC-028',
                'address' => 'Narok Town',
                'latitude' => -1.099038,
                'longitude' => 35.85855,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Ngoigwa Branch',
                'code' => 'KPFC-029',
                'address' => 'Thika Town',
                'latitude' => -1.041534,
                'longitude' => 37.050054,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Ngong Branch',
                'code' => 'KPFC-030',
                'address' => 'Ngong Branch',
                'latitude' => -1.347665,
                'longitude' => 36.662323,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Nyahururu Branch',
                'code' => 'KPFC-031',
                'address' => 'Nyahururu Town',
                'latitude' => 0.0255615,
                'longitude' => 36.3653307,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Nyeri Branch',
                'code' => 'KPFC-032',
                'address' => 'Nyeri Town',
                'latitude' => -0.426038,
                'longitude' => 36.956741,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Rongai Branch',
                'code' => 'KPFC-033',
                'address' => 'Kajiado Town',
                'latitude' => -1.389958,
                'longitude' => 36.767485,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Ruaka Branch',
                'code' => 'KPFC-034',
                'address' => 'Ruaka Town',
                'latitude' => -1.20101,
                'longitude' => 36.763872,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Ruthigiti Branch',
                'code' => 'KPFC-035',
                'address' => 'Ruthigiti Town',
                'latitude' => -1.276964,
                'longitude' => 36.611522,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Shop 1 Branch',
                'code' => 'KPFC-036',
                'address' => 'Kikuyu Town',
                'latitude' => -1.244118,
                'longitude' => 36.665405,
                'radius_meters' => 200,
                'active' => true,
            ],
            [
                'name' => 'Thika Branch',
                'code' => 'KPFC-037',
                'address' => 'Thika Town',
                'latitude' => -1.042775,
                'longitude' => 37.069689,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Thogoto Branch',
                'code' => 'KPFC-038',
                'address' => 'Thogoto Town - Along Southern Bypass',
                'latitude' => -1.27455,
                'longitude' => 36.665701,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Uthiru Branch',
                'code' => 'KPFC-039',
                'address' => 'Uthiru Town',
                'latitude' => -1.260186,
                'longitude' => 36.7184493,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Voi Branch',
                'code' => 'KPFC-040',
                'address' => 'Voi Town',
                'latitude' => -3.403666,
                'longitude' => 38.589475,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Wangige Branch',
                'code' => 'KPFC-041',
                'address' => 'Wangige Town',
                'latitude' => -1.220763,
                'longitude' => 36.714852,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Narumoro Branch',
                'code' => 'KPFC-042',
                'address' => 'Narumoro Town',
                'latitude' => -0.175639,
                'longitude' => 37.022139,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Chaka Branch',
                'code' => 'KPFC-043',
                'address' => 'Chaka Town',
                'latitude' => -0.363974,
                'longitude' => 37.000173,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Nyeri-Skuta Branch',
                'code' => 'KPFC-044',
                'address' => 'Skuta Town',
                'latitude' => -0.4329026,
                'longitude' => 36.9665317,
                'radius_meters' => 450,
                'active' => true,
            ],
            [
                'name' => 'Gikambura Branch',
                'code' => 'KPFC-045',
                'address' => 'Gikambura - Opposite Shell Petrol Station',
                'latitude' => -1.281284,
                'longitude' => 36.656241,
                'radius_meters' => 450,
                'active' => true,
            ],
        ];

        foreach ($shops as $shop) {
            Shop::updateOrCreate(
                ['code' => $shop['code']],
                $shop
            );
        }
    }
}