server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param HTTP_X_REAL_IP $http_x_real_ip if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host if_not_empty;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization if_not_empty;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    client_max_body_size 50M;
}